### PR TITLE
Add Features to Dev Branch

### PR DESCRIPTION
**Pull request by MephistoDevelop**
Features Added:
-Game Flow Logic
-Factory functions
-Board Design
-Fix linter files
- Fix Logic of game play

### CODE REVIEW

**Comment by bellom** [comment]
**Always leave a comment whenever it happens you close a PR without approval.
I guess the reason was because of the `linter` error, if that should be the case it might not be obvious to everyone.**

From the previous review, you were asked to use the provided `eslint.config` by Microverse.
But you added this line 👉`"no-restricted-syntax": ["error", "FunctionExpression", "WithStatement", "BinaryExpression[operator='in']"]`
**Kindly talk about the reason and is it valid enough to raise a PR to the repo with the suggested changes **

image
https://github.com/MephistoDevelop/tic-tac-toe-game/pull/1

**Comment by bellom** [comment]
This could help 👉 https://stackoverflow.com/questions/39252743/how-do-i-resolve-the-no-restricted-syntax-from-eslinter-in-javascript

**Comment by MephistoDevelop** [comment]
Closed by problems on Linter files, task do it before closed this pull request:
Repair Linter files
Use original microverse configuration to lintern.

**Comment by bellom** [comment]
😳 where could our linter be?

**Comment by bellom** [comment]
> Closed by problems on Linter files, task do it before closed this pull request:
> Repair Linter files
> Use original microverse configuration to lintern.

Ok

**Review by bellom — CHANGES_REQUESTED** [review]
**Always leave a comment whenever it happens you close a PR without approval.
I guess the reason was because of the `linter` error, if that should be the case it might not be obvious to everyone.**

From the previous review, you were asked to use the provided `eslint.config` by Microverse.
But you added this line 👉`"no-restricted-syntax": ["error", "FunctionExpression", "WithStatement", "BinaryExpression[operator='in']"]`
**Kindly talk about the reason and is it valid enough to raise a PR to the repo with the suggested changes **

image
https://github.com/MephistoDevelop/tic-tac-toe-game/pull/1

**Pull request closed without merging**
